Repository nextcloud/Android-SingleSignOn, pull requests merged in 2024-01, with the labels that each got.

#629 chore: AGP 8 and Java 17
  .drone.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  jitpack.yml
  lib/build.gradle
  sample/build.gradle
Labels: 3. to release

#560 chore: Remove deprecations
  lib/src/main/java/com/nextcloud/android/sso/api/AidlNetworkRequest.java
  lib/src/main/java/com/nextcloud/android/sso/api/NetworkRequest.java
  lib/src/main/java/com/nextcloud/android/sso/api/NextcloudAPI.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/AccountImportCancelledException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/AndroidGetAccountsPermissionNotGranted.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/CurrentAccountNotFoundException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudApiNotRespondingException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudFilesAppAccountNotFoundException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudFilesAppAccountPermissionNotGrantedException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudFilesAppNotInstalledException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudFilesAppNotSupportedException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudHttpRequestFailedException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudInvalidRequestUrlException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NextcloudUnsupportedMethodException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/NoCurrentAccountSelectedException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/SSOException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/TokenMismatchException.java
  lib/src/main/java/com/nextcloud/android/sso/exceptions/UnknownErrorException.java
  lib/src/main/java/com/nextcloud/android/sso/helper/ExponentialBackoff.java
  lib/src/main/java/com/nextcloud/android/sso/helper/SingleAccountHelper.java
  lib/src/main/java/com/nextcloud/android/sso/model/ExceptionMessage.java
  lib/src/main/java/com/nextcloud/android/sso/ui/UiExceptionManager.java
Labels: 3. to release

#632 Update codacy badge
  README.md
Labels: 1. developing

#639 Bump AGP to 8.2.2
  build.gradle
Labels: 3. to release

#636 add migration info for Void -> EmptyResponse
  README.md
  lib/src/main/java/com/nextcloud/android/sso/api/NextcloudAPI.java
  lib/src/main/java/com/nextcloud/android/sso/helper/Retrofit2Helper.java
Labels: 3. to review

#649 Update spotbugs-gradle-plugin
  build.gradle
  lib/build.gradle
  scripts/analysis/findbugs-up.rb
Labels: dependencies, 3. to review, technical debt

#648 Add dependency checksums and signing key information
  .gitignore
  gradle.properties
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 4. to release

#651 Add packaging dependency checksums
  gradle/verification-keyring.keys
  gradle/verification-metadata.xml
Labels: 2. developing
