Repository nextcloud/Android-SingleSignOn, pull requests merged in 2024-07, with the labels that each got.

#725 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#727 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#732 Fix tensorflow dependency meta data
  gradle/verification-metadata.xml
Labels: bug, dependencies, 3. to review
